# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPlainTextEdit, QPushButton,
    QScrollArea, QSizePolicy, QStackedWidget, QTabWidget,
    QTableView, QTableWidget, QTableWidgetItem, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1230, 880)
        MainWindow.setMinimumSize(QSize(1230, 880))
        icon = QIcon()
        icon.addFile(u":/icon_small/CVIcaja.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1230, 880))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QSize(1230, 880))
        font = QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(u"background-color:rgb(222, 221, 218)")
        self.Login = QWidget()
        self.Login.setObjectName(u"Login")
        self.Login.setAutoFillBackground(False)
        self.wrong_up_label = QLabel(self.Login)
        self.wrong_up_label.setObjectName(u"wrong_up_label")
        self.wrong_up_label.setGeometry(QRect(480, 650, 271, 21))
        font1 = QFont()
        font1.setKerning(True)
        self.wrong_up_label.setFont(font1)
        self.wrong_up_label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.wrong_up_label.setScaledContents(False)
        self.wrong_up_label.setAlignment(Qt.AlignCenter)
        self.user_label = QLabel(self.Login)
        self.user_label.setObjectName(u"user_label")
        self.user_label.setGeometry(QRect(480, 480, 80, 21))
        font2 = QFont()
        font2.setPointSize(12)
        self.user_label.setFont(font2)
        self.user_label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.Pass_le = QLineEdit(self.Login)
        self.Pass_le.setObjectName(u"Pass_le")
        self.Pass_le.setGeometry(QRect(470, 600, 291, 41))
        font3 = QFont()
        font3.setPointSize(15)
        self.Pass_le.setFont(font3)
        self.Pass_le.setFocusPolicy(Qt.ClickFocus)
        self.Pass_le.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px;color:black")
        self.Pass_le.setEchoMode(QLineEdit.Password)
        self.login_btn = QPushButton(self.Login)
        self.login_btn.setObjectName(u"login_btn")
        self.login_btn.setGeometry(QRect(820, 730, 201, 47))
        font4 = QFont()
        font4.setBold(True)
        self.login_btn.setFont(font4)
        self.login_btn.setFocusPolicy(Qt.TabFocus)
        self.login_btn.setAutoFillBackground(False)
        self.login_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.login_btn.setAutoRepeat(False)
        self.exit_btn = QPushButton(self.Login)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(200, 730, 201, 47))
        self.exit_btn.setFont(font4)
        self.exit_btn.setFocusPolicy(Qt.TabFocus)
        self.exit_btn.setAutoFillBackground(False)
        self.exit_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.exit_btn.setAutoRepeat(False)
        self.logo_label = QLabel(self.Login)
        self.logo_label.setObjectName(u"logo_label")
        self.logo_label.setGeometry(QRect(470, 60, 301, 281))
        self.logo_label.setStyleSheet(u"backgrund-color:rgba(0,0,0,0);")
        self.logo_label.setText(u"")
        self.logo_label.setTextFormat(Qt.AutoText)
        self.logo_label.setPixmap(QPixmap(u":/icon_big/LogoBig.png"))
        self.logo_label.setScaledContents(True)
        self.pass_label = QLabel(self.Login)
        self.pass_label.setObjectName(u"pass_label")
        self.pass_label.setGeometry(QRect(480, 570, 111, 21))
        self.pass_label.setFont(font2)
        self.pass_label.setStyleSheet(u"background-color:rgba(0,0,0,0);color:black")
        self.Login_combobox = QComboBox(self.Login)
        self.Login_combobox.addItem("")
        self.Login_combobox.addItem("")
        self.Login_combobox.addItem("")
        self.Login_combobox.setObjectName(u"Login_combobox")
        self.Login_combobox.setGeometry(QRect(470, 510, 291, 41))
        self.Login_combobox.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px\n"
";color:black;")
        self.stackedWidget.addWidget(self.Login)
        self.Caja = QWidget()
        self.Caja.setObjectName(u"Caja")
        self.Caja.setAutoFillBackground(False)
        self.Caja.setStyleSheet(u"background-color:rgb(222, 221, 218)")
        self.tab_caja = QTabWidget(self.Caja)
        self.tab_caja.setObjectName(u"tab_caja")
        self.tab_caja.setGeometry(QRect(10, 130, 1161, 681))
        self.tab_caja.setStyleSheet(u"background-color:rgb(222, 221, 218);color:black")
        self.tab_venta = QWidget()
        self.tab_venta.setObjectName(u"tab_venta")
        self.label_search_2 = QLabel(self.tab_venta)
        self.label_search_2.setObjectName(u"label_search_2")
        self.label_search_2.setGeometry(QRect(10, 20, 70, 31))
        self.label_search_2.setFont(font3)
        self.inv_le_2 = QLineEdit(self.tab_venta)
        self.inv_le_2.setObjectName(u"inv_le_2")
        self.inv_le_2.setGeometry(QRect(200, 20, 491, 31))
        self.inv_le_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.inv_comboBox_2 = QComboBox(self.tab_venta)
        self.inv_comboBox_2.addItem("")
        self.inv_comboBox_2.addItem("")
        self.inv_comboBox_2.setObjectName(u"inv_comboBox_2")
        self.inv_comboBox_2.setGeometry(QRect(90, 20, 101, 31))
        self.venta_btn = QPushButton(self.tab_venta)
        self.venta_btn.setObjectName(u"venta_btn")
        self.venta_btn.setGeometry(QRect(1020, 20, 121, 31))
        self.venta_btn.setFont(font4)
        self.venta_btn.setAutoFillBackground(False)
        self.venta_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.venta_btn.setAutoRepeat(False)
        self.horizontalLayoutWidget = QWidget(self.tab_venta)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 90, 1161, 571))
        self.HLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout.setObjectName(u"HLayout")
        self.HLayout.setContentsMargins(0, 0, 0, 0)
        self.table_busq = QTableView(self.tab_venta)
        self.table_busq.setObjectName(u"table_busq")
        self.table_busq.setGeometry(QRect(200, 50, 491, 211))
        self.tab_caja.addTab(self.tab_venta, "")
        self.tab_inventario = QWidget()
        self.tab_inventario.setObjectName(u"tab_inventario")
        self.table_inv = QTableView(self.tab_inventario)
        self.table_inv.setObjectName(u"table_inv")
        self.table_inv.setGeometry(QRect(10, 180, 1141, 481))
        self.inv_le = QLineEdit(self.tab_inventario)
        self.inv_le.setObjectName(u"inv_le")
        self.inv_le.setGeometry(QRect(300, 10, 841, 31))
        self.inv_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.inv_comboBox = QComboBox(self.tab_inventario)
        self.inv_comboBox.addItem("")
        self.inv_comboBox.addItem("")
        self.inv_comboBox.setObjectName(u"inv_comboBox")
        self.inv_comboBox.setGeometry(QRect(110, 10, 181, 31))
        self.label_search = QLabel(self.tab_inventario)
        self.label_search.setObjectName(u"label_search")
        self.label_search.setGeometry(QRect(30, 10, 71, 31))
        self.label_search.setFont(font3)
        self.label_2 = QLabel(self.tab_inventario)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 60, 66, 17))
        self.code_le = QLineEdit(self.tab_inventario)
        self.code_le.setObjectName(u"code_le")
        self.code_le.setGeometry(QRect(30, 80, 141, 25))
        self.code_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.label_3 = QLabel(self.tab_inventario)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 60, 131, 17))
        self.prod_le = QLineEdit(self.tab_inventario)
        self.prod_le.setObjectName(u"prod_le")
        self.prod_le.setGeometry(QRect(180, 80, 441, 25))
        self.prod_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.label_4 = QLabel(self.tab_inventario)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(630, 60, 101, 17))
        self.Smin_le = QLineEdit(self.tab_inventario)
        self.Smin_le.setObjectName(u"Smin_le")
        self.Smin_le.setGeometry(QRect(630, 80, 71, 25))
        self.Smin_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.label_5 = QLabel(self.tab_inventario)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(730, 60, 101, 17))
        self.Smax_le = QLineEdit(self.tab_inventario)
        self.Smax_le.setObjectName(u"Smax_le")
        self.Smax_le.setGeometry(QRect(740, 80, 71, 25))
        self.Smax_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.label_6 = QLabel(self.tab_inventario)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(840, 60, 101, 17))
        self.Sact_le = QLineEdit(self.tab_inventario)
        self.Sact_le.setObjectName(u"Sact_le")
        self.Sact_le.setGeometry(QRect(840, 80, 71, 25))
        self.Sact_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.label_7 = QLabel(self.tab_inventario)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(960, 60, 101, 17))
        self.lab_le = QLineEdit(self.tab_inventario)
        self.lab_le.setObjectName(u"lab_le")
        self.lab_le.setGeometry(QRect(960, 80, 181, 25))
        self.lab_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.mod_btn = QPushButton(self.tab_inventario)
        self.mod_btn.setObjectName(u"mod_btn")
        self.mod_btn.setGeometry(QRect(30, 130, 171, 31))
        self.mod_btn.setFont(font4)
        self.mod_btn.setAutoFillBackground(False)
        self.mod_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.mod_btn.setAutoRepeat(False)
        self.add_new_btn = QPushButton(self.tab_inventario)
        self.add_new_btn.setObjectName(u"add_new_btn")
        self.add_new_btn.setGeometry(QRect(970, 130, 171, 31))
        self.add_new_btn.setFont(font4)
        self.add_new_btn.setAutoFillBackground(False)
        self.add_new_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_new_btn.setAutoRepeat(False)
        self.tab_caja.addTab(self.tab_inventario, "")
        self.faltantes_tab = QWidget()
        self.faltantes_tab.setObjectName(u"faltantes_tab")
        self.tableWidget = QTableWidget(self.faltantes_tab)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 80, 1161, 571))
        self.tab_caja.addTab(self.faltantes_tab, "")
        self.tab_estetica = QWidget()
        self.tab_estetica.setObjectName(u"tab_estetica")
        self.contenedor_esetetica = QScrollArea(self.tab_estetica)
        self.contenedor_esetetica.setObjectName(u"contenedor_esetetica")
        self.contenedor_esetetica.setGeometry(QRect(0, 130, 1161, 471))
        self.contenedor_esetetica.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 1159, 469))
        self.contenedor_esetetica.setWidget(self.scrollAreaWidgetContents_2)
        self.add_estetica_btn = QPushButton(self.tab_estetica)
        self.add_estetica_btn.setObjectName(u"add_estetica_btn")
        self.add_estetica_btn.setGeometry(QRect(10, 90, 131, 31))
        self.add_estetica_btn.setFont(font4)
        self.add_estetica_btn.setAutoFillBackground(False)
        self.add_estetica_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_estetica_btn.setAutoRepeat(False)
        self.label_8 = QLabel(self.tab_estetica)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 81, 17))
        self.lineEdit = QLineEdit(self.tab_estetica)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 151, 31))
        self.lineEdit.setFont(font2)
        self.lineEdit_2 = QLineEdit(self.tab_estetica)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(180, 30, 181, 31))
        self.lineEdit_2.setFont(font2)
        self.label_9 = QLabel(self.tab_estetica)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(180, 10, 66, 17))
        self.checkBox = QCheckBox(self.tab_estetica)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(410, 30, 71, 23))
        self.checkBox_2 = QCheckBox(self.tab_estetica)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(410, 60, 71, 23))
        self.checkBox_3 = QCheckBox(self.tab_estetica)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(520, 30, 81, 23))
        self.checkBox_4 = QCheckBox(self.tab_estetica)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(520, 60, 131, 23))
        self.checkBox_5 = QCheckBox(self.tab_estetica)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(520, 90, 81, 23))
        self.add_estetica_btn_2 = QPushButton(self.tab_estetica)
        self.add_estetica_btn_2.setObjectName(u"add_estetica_btn_2")
        self.add_estetica_btn_2.setGeometry(QRect(1000, 610, 131, 31))
        self.add_estetica_btn_2.setFont(font4)
        self.add_estetica_btn_2.setAutoFillBackground(False)
        self.add_estetica_btn_2.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_estetica_btn_2.setAutoRepeat(False)
        self.checkBox_6 = QCheckBox(self.tab_estetica)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(690, 60, 81, 23))
        self.label_10 = QLabel(self.tab_estetica)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(900, 20, 131, 17))
        self.lineEdit_3 = QLineEdit(self.tab_estetica)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(790, 50, 351, 31))
        self.lineEdit_3.setFont(font2)
        self.tab_caja.addTab(self.tab_estetica, "")
        self.Logo_label_2 = QLabel(self.Caja)
        self.Logo_label_2.setObjectName(u"Logo_label_2")
        self.Logo_label_2.setGeometry(QRect(30, 20, 81, 81))
        self.Logo_label_2.setPixmap(QPixmap(u":/icon_small/CVIcaja.png"))
        self.exit_btn_3 = QPushButton(self.Caja)
        self.exit_btn_3.setObjectName(u"exit_btn_3")
        self.exit_btn_3.setGeometry(QRect(20, 830, 171, 31))
        self.exit_btn_3.setFont(font4)
        self.exit_btn_3.setAutoFillBackground(False)
        self.exit_btn_3.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.exit_btn_3.setAutoRepeat(False)
        self.stackedWidget.addWidget(self.Caja)
        self.Consul = QWidget()
        self.Consul.setObjectName(u"Consul")
        self.exit_btn_2 = QPushButton(self.Consul)
        self.exit_btn_2.setObjectName(u"exit_btn_2")
        self.exit_btn_2.setGeometry(QRect(10, 820, 171, 31))
        self.exit_btn_2.setFont(font4)
        self.exit_btn_2.setAutoFillBackground(False)
        self.exit_btn_2.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.exit_btn_2.setAutoRepeat(False)
        self.send_btn = QPushButton(self.Consul)
        self.send_btn.setObjectName(u"send_btn")
        self.send_btn.setGeometry(QRect(1030, 820, 171, 31))
        self.send_btn.setFont(font4)
        self.send_btn.setAutoFillBackground(False)
        self.send_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.send_btn.setAutoRepeat(False)
        self.Logo_label = QLabel(self.Consul)
        self.Logo_label.setObjectName(u"Logo_label")
        self.Logo_label.setGeometry(QRect(20, 10, 161, 161))
        self.Logo_label.setPixmap(QPixmap(u":/icon_mid/LogoMid.png"))
        self.mvz_lbl = QLabel(self.Consul)
        self.mvz_lbl.setObjectName(u"mvz_lbl")
        self.mvz_lbl.setGeometry(QRect(210, 100, 91, 31))
        self.mvz_lbl.setFont(font3)
        self.mvz_lbl.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.paciente_lbl = QLabel(self.Consul)
        self.paciente_lbl.setObjectName(u"paciente_lbl")
        self.paciente_lbl.setGeometry(QRect(210, 40, 91, 31))
        self.paciente_lbl.setFont(font3)
        self.paciente_lbl.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.label = QLabel(self.Consul)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 190, 81, 31))
        self.label.setFont(font3)
        self.label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.paciente_le = QLineEdit(self.Consul)
        self.paciente_le.setObjectName(u"paciente_le")
        self.paciente_le.setGeometry(QRect(330, 40, 321, 29))
        self.paciente_le.setFont(font3)
        self.paciente_le.setStyleSheet(u"color:black;")
        self.remove_btn = QPushButton(self.Consul)
        self.remove_btn.setObjectName(u"remove_btn")
        self.remove_btn.setGeometry(QRect(630, 820, 131, 31))
        self.remove_btn.setFont(font4)
        self.remove_btn.setAutoFillBackground(False)
        self.remove_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.remove_btn.setAutoRepeat(False)
        self.add_btn = QPushButton(self.Consul)
        self.add_btn.setObjectName(u"add_btn")
        self.add_btn.setGeometry(QRect(810, 820, 131, 31))
        self.add_btn.setFont(font4)
        self.add_btn.setAutoFillBackground(False)
        self.add_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_btn.setAutoRepeat(False)
        self.busq_consul_le = QLineEdit(self.Consul)
        self.busq_consul_le.setObjectName(u"busq_consul_le")
        self.busq_consul_le.setGeometry(QRect(280, 190, 491, 31))
        self.busq_consul_le.setStyleSheet(u"color:black;")
        self.mvz_comboBox = QComboBox(self.Consul)
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.setObjectName(u"mvz_comboBox")
        self.mvz_comboBox.setGeometry(QRect(330, 100, 271, 31))
        self.mvz_comboBox.setStyleSheet(u"color:black")
        self.busca_cuenta = QTableView(self.Consul)
        self.busca_cuenta.setObjectName(u"busca_cuenta")
        self.busca_cuenta.setGeometry(QRect(20, 240, 751, 521))
        self.busca_cuenta.setStyleSheet(u"color:black;")
        self.wrong_dr = QLabel(self.Consul)
        self.wrong_dr.setObjectName(u"wrong_dr")
        self.wrong_dr.setGeometry(QRect(330, 140, 171, 17))
        self.wrong_dr.setStyleSheet(u"color:red")
        self.label_cuenta = QLabel(self.Consul)
        self.label_cuenta.setObjectName(u"label_cuenta")
        self.label_cuenta.setGeometry(QRect(790, 440, 101, 31))
        self.label_cuenta.setFont(font3)
        self.label_cuenta.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.consul_comboBox = QComboBox(self.Consul)
        self.consul_comboBox.addItem("")
        self.consul_comboBox.addItem("")
        self.consul_comboBox.addItem("")
        self.consul_comboBox.setObjectName(u"consul_comboBox")
        self.consul_comboBox.setGeometry(QRect(110, 190, 151, 31))
        self.consul_comboBox.setStyleSheet(u"color:black")
        self.wrong_pet = QLabel(self.Consul)
        self.wrong_pet.setObjectName(u"wrong_pet")
        self.wrong_pet.setGeometry(QRect(330, 70, 281, 17))
        self.wrong_pet.setStyleSheet(u"color:red")
        self.table_cuenta = QTableWidget(self.Consul)
        self.table_cuenta.setObjectName(u"table_cuenta")
        self.table_cuenta.setGeometry(QRect(800, 480, 401, 281))
        self.table_cuenta.setStyleSheet(u"color:black;")
        self.label_total = QLabel(self.Consul)
        self.label_total.setObjectName(u"label_total")
        self.label_total.setGeometry(QRect(800, 770, 231, 31))
        self.label_total.setFont(font3)
        self.label_total.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.paciente_lbl_2 = QLabel(self.Consul)
        self.paciente_lbl_2.setObjectName(u"paciente_lbl_2")
        self.paciente_lbl_2.setGeometry(QRect(670, 49, 80, 21))
        self.paciente_lbl_2.setFont(font3)
        self.paciente_lbl_2.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.especie_le_ = QLineEdit(self.Consul)
        self.especie_le_.setObjectName(u"especie_le_")
        self.especie_le_.setGeometry(QRect(750, 40, 321, 29))
        self.especie_le_.setFont(font3)
        self.especie_le_.setStyleSheet(u"color:black;")
        self.paciente_lbl_3 = QLabel(self.Consul)
        self.paciente_lbl_3.setObjectName(u"paciente_lbl_3")
        self.paciente_lbl_3.setGeometry(QRect(690, 100, 51, 21))
        self.paciente_lbl_3.setFont(font3)
        self.paciente_lbl_3.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.raza_le = QLineEdit(self.Consul)
        self.raza_le.setObjectName(u"raza_le")
        self.raza_le.setGeometry(QRect(750, 100, 321, 29))
        self.raza_le.setFont(font3)
        self.raza_le.setStyleSheet(u"color:black;")
        self.label_tx = QLabel(self.Consul)
        self.label_tx.setObjectName(u"label_tx")
        self.label_tx.setGeometry(QRect(790, 200, 121, 31))
        self.label_tx.setFont(font3)
        self.label_tx.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.tx_TE = QPlainTextEdit(self.Consul)
        self.tx_TE.setObjectName(u"tx_TE")
        self.tx_TE.setGeometry(QRect(800, 240, 401, 81))
        self.nota_le = QLabel(self.Consul)
        self.nota_le.setObjectName(u"nota_le")
        self.nota_le.setGeometry(QRect(790, 320, 121, 31))
        self.nota_le.setFont(font3)
        self.nota_le.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.tx_TE_2 = QPlainTextEdit(self.Consul)
        self.tx_TE_2.setObjectName(u"tx_TE_2")
        self.tx_TE_2.setGeometry(QRect(800, 360, 401, 71))
        self.stackedWidget.addWidget(self.Consul)
        self.Admin = QWidget()
        self.Admin.setObjectName(u"Admin")
        self.admin_SE_button = QPushButton(self.Admin)
        self.admin_SE_button.setObjectName(u"admin_SE_button")
        self.admin_SE_button.setGeometry(QRect(490, 700, 241, 61))
        font5 = QFont()
        font5.setPointSize(22)
        self.admin_SE_button.setFont(font5)
        self.admin_SE_button.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.IP_caja_le = QLineEdit(self.Admin)
        self.IP_caja_le.setObjectName(u"IP_caja_le")
        self.IP_caja_le.setGeometry(QRect(540, 140, 331, 41))
        font6 = QFont()
        font6.setPointSize(16)
        self.IP_caja_le.setFont(font6)
        self.IP_caja_le.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px;color:black")
        self.IP_label = QLabel(self.Admin)
        self.IP_label.setObjectName(u"IP_label")
        self.IP_label.setGeometry(QRect(370, 140, 161, 41))
        font7 = QFont()
        font7.setPointSize(25)
        self.IP_label.setFont(font7)
        self.IP_label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.label_doctores = QLabel(self.Admin)
        self.label_doctores.setObjectName(u"label_doctores")
        self.label_doctores.setGeometry(QRect(370, 220, 161, 41))
        self.label_doctores.setFont(font7)
        self.label_doctores.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.admin_add_dr = QPushButton(self.Admin)
        self.admin_add_dr.setObjectName(u"admin_add_dr")
        self.admin_add_dr.setGeometry(QRect(840, 220, 171, 51))
        font8 = QFont()
        font8.setPointSize(14)
        self.admin_add_dr.setFont(font8)
        self.admin_add_dr.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.admin_rmv_dr = QPushButton(self.Admin)
        self.admin_rmv_dr.setObjectName(u"admin_rmv_dr")
        self.admin_rmv_dr.setGeometry(QRect(840, 280, 171, 51))
        self.admin_rmv_dr.setFont(font8)
        self.admin_rmv_dr.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.listWidget = QListWidget(self.Admin)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(540, 230, 256, 192))
        self.listWidget.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px;color:black")
        self.stackedWidget.addWidget(self.Admin)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.login_btn.setDefault(False)
        self.exit_btn.setDefault(False)
        self.tab_caja.setCurrentIndex(0)
        self.venta_btn.setDefault(False)
        self.mod_btn.setDefault(False)
        self.add_new_btn.setDefault(False)
        self.add_estetica_btn.setDefault(False)
        self.add_estetica_btn_2.setDefault(False)
        self.exit_btn_3.setDefault(False)
        self.exit_btn_2.setDefault(False)
        self.send_btn.setDefault(False)
        self.remove_btn.setDefault(False)
        self.add_btn.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.wrong_up_label.setText(QCoreApplication.translate("MainWindow", u"Contrase\u00f1a incorrecta", None))
        self.user_label.setText(QCoreApplication.translate("MainWindow", u"Usuario:", None))
        self.Pass_le.setText("")
        self.login_btn.setText(QCoreApplication.translate("MainWindow", u"Iniciar Sesi\u00f3n", None))
        self.exit_btn.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.pass_label.setText(QCoreApplication.translate("MainWindow", u"Contrase\u00f1a:", None))
        self.Login_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"Consultorio", None))
        self.Login_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"Caja", None))
        self.Login_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"Admin", None))

        self.label_search_2.setText(QCoreApplication.translate("MainWindow", u"Buscar:", None))
        self.inv_comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"productos", None))
        self.inv_comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"servicios", None))

        self.venta_btn.setText(QCoreApplication.translate("MainWindow", u"Nueva Venta", None))
#if QT_CONFIG(shortcut)
        self.venta_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_venta), QCoreApplication.translate("MainWindow", u"Venta", None))
        self.inv_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"productos", None))
        self.inv_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"servicios", None))

        self.label_search.setText(QCoreApplication.translate("MainWindow", u"Buscar:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Producto/Servicio", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Stock m\u00ednimo", None))
        self.Smin_le.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Stock m\u00e1ximo", None))
        self.Smax_le.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Stock Actual", None))
        self.Sact_le.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Laboratorio", None))
        self.lab_le.setText("")
        self.mod_btn.setText(QCoreApplication.translate("MainWindow", u"Modificar", None))
#if QT_CONFIG(shortcut)
        self.mod_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.add_new_btn.setText(QCoreApplication.translate("MainWindow", u"Agregar Nuevo", None))
#if QT_CONFIG(shortcut)
        self.add_new_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_inventario), QCoreApplication.translate("MainWindow", u"Inventario", None))
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.faltantes_tab), QCoreApplication.translate("MainWindow", u"Faltantes", None))
        self.add_estetica_btn.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
#if QT_CONFIG(shortcut)
        self.add_estetica_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Mascota(s):", None))
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Tel\u00e9fono:", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Ba\u00f1o", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Corte", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Vacunas", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Desparasitaci\u00f3n", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Consulta", None))
        self.add_estetica_btn_2.setText(QCoreApplication.translate("MainWindow", u"Quitar", None))
#if QT_CONFIG(shortcut)
        self.add_estetica_btn_2.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Pagado", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Notas Adicionales:", None))
        self.lineEdit_3.setText("")
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_estetica), QCoreApplication.translate("MainWindow", u"Est\u00e9tica", None))
        self.Logo_label_2.setText("")
        self.exit_btn_3.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.exit_btn_3.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.exit_btn_2.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.exit_btn_2.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.send_btn.setText(QCoreApplication.translate("MainWindow", u"Enviar", None))
#if QT_CONFIG(shortcut)
        self.send_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.Logo_label.setText("")
        self.mvz_lbl.setText(QCoreApplication.translate("MainWindow", u"Doctor(a):", None))
        self.paciente_lbl.setText(QCoreApplication.translate("MainWindow", u"Paciente:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Servicio:", None))
        self.remove_btn.setText(QCoreApplication.translate("MainWindow", u"Quitar", None))
#if QT_CONFIG(shortcut)
        self.remove_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.add_btn.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
#if QT_CONFIG(shortcut)
        self.add_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.mvz_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Seleccione", None))
        self.mvz_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"M.V.Z. Brenda", None))
        self.mvz_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"M.V.Z. Janeth", None))
        self.mvz_comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"M.V.Z. Juan", None))
        self.mvz_comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"M.V.Z. Angelica", None))

        self.wrong_dr.setText(QCoreApplication.translate("MainWindow", u"Seleccione quien atendi\u00f3", None))
        self.label_cuenta.setText(QCoreApplication.translate("MainWindow", u"Cuenta:", None))
        self.consul_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"productos", None))
        self.consul_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"servicios", None))
        self.consul_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Pacientes", None))

        self.wrong_pet.setText(QCoreApplication.translate("MainWindow", u"Ingrese nombre de mascota o propietario", None))
        self.label_total.setText(QCoreApplication.translate("MainWindow", u"Total: $", None))
        self.paciente_lbl_2.setText(QCoreApplication.translate("MainWindow", u"Especie:", None))
        self.paciente_lbl_3.setText(QCoreApplication.translate("MainWindow", u"Raza:", None))
        self.label_tx.setText(QCoreApplication.translate("MainWindow", u"Tratamiento:", None))
        self.nota_le.setText(QCoreApplication.translate("MainWindow", u"Notas:", None))
        self.admin_SE_button.setText(QCoreApplication.translate("MainWindow", u"Guardar y salir", None))
        self.IP_label.setText(QCoreApplication.translate("MainWindow", u"IP de Caja:", None))
        self.label_doctores.setText(QCoreApplication.translate("MainWindow", u"Doctores", None))
        self.admin_add_dr.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.admin_rmv_dr.setText(QCoreApplication.translate("MainWindow", u"Quitar", None))
    # retranslateUi

