# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.13
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1230, 880)
        MainWindow.setMinimumSize(QSize(1230, 880))
        MainWindow.setMaximumSize(QSize(1230, 880))
        icon = QIcon()
        icon.addFile(u":/icon_small/CVIcaja.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1230, 880))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QSize(1230, 880))
        self.stackedWidget.setMaximumSize(QSize(1230, 880))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(u"background-color:rgb(222, 221, 218)")
        self.Login = QWidget()
        self.Login.setObjectName(u"Login")
        self.Login.setAutoFillBackground(False)
        self.wrong_up_label = QLabel(self.Login)
        self.wrong_up_label.setObjectName(u"wrong_up_label")
        self.wrong_up_label.setGeometry(QRect(480, 650, 271, 21))
        font = QFont()
        font.setKerning(True)
        self.wrong_up_label.setFont(font)
        self.wrong_up_label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.wrong_up_label.setScaledContents(False)
        self.wrong_up_label.setAlignment(Qt.AlignCenter)
        self.user_label = QLabel(self.Login)
        self.user_label.setObjectName(u"user_label")
        self.user_label.setGeometry(QRect(480, 480, 80, 21))
        font1 = QFont()
        font1.setPointSize(12)
        self.user_label.setFont(font1)
        self.user_label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.Pass_le = QLineEdit(self.Login)
        self.Pass_le.setObjectName(u"Pass_le")
        self.Pass_le.setGeometry(QRect(470, 600, 291, 41))
        font2 = QFont()
        font2.setPointSize(15)
        self.Pass_le.setFont(font2)
        self.Pass_le.setFocusPolicy(Qt.TabFocus)
        self.Pass_le.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px;color:black")
        self.Pass_le.setEchoMode(QLineEdit.Password)
        self.login_btn = QPushButton(self.Login)
        self.login_btn.setObjectName(u"login_btn")
        self.login_btn.setGeometry(QRect(820, 730, 201, 47))
        font3 = QFont()
        font3.setBold(True)
        font3.setLegacyWeight(75)
        self.login_btn.setFont(font3)
        self.login_btn.setFocusPolicy(Qt.TabFocus)
        self.login_btn.setAutoFillBackground(False)
        self.login_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.login_btn.setAutoRepeat(False)
        self.exit_btn = QPushButton(self.Login)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(200, 730, 201, 47))
        self.exit_btn.setFont(font3)
        self.exit_btn.setFocusPolicy(Qt.TabFocus)
        self.exit_btn.setAutoFillBackground(False)
        self.exit_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:20px;")
        self.exit_btn.setAutoRepeat(False)
        self.logo_label = QLabel(self.Login)
        self.logo_label.setObjectName(u"logo_label")
        self.logo_label.setGeometry(QRect(470, 60, 301, 281))
        self.logo_label.setStyleSheet(u"backgrund-color:rgba(0,0,0,0);")
        self.logo_label.setText(u"")
        self.logo_label.setTextFormat(Qt.AutoText)
        self.logo_label.setPixmap(QPixmap(u":/icon_big/LogoBig.png"))
        self.logo_label.setScaledContents(True)
        self.pass_label = QLabel(self.Login)
        self.pass_label.setObjectName(u"pass_label")
        self.pass_label.setGeometry(QRect(480, 570, 111, 21))
        self.pass_label.setFont(font1)
        self.pass_label.setStyleSheet(u"background-color:rgba(0,0,0,0);color:black")
        self.Login_combobox = QComboBox(self.Login)
        self.Login_combobox.addItem("")
        self.Login_combobox.addItem("")
        self.Login_combobox.addItem("")
        self.Login_combobox.setObjectName(u"Login_combobox")
        self.Login_combobox.setGeometry(QRect(470, 510, 291, 41))
        self.Login_combobox.setStyleSheet(u"background-color:rgb(192, 191, 188);border-radius:10px\n"
";color:black;")
        self.stackedWidget.addWidget(self.Login)
        self.Caja = QWidget()
        self.Caja.setObjectName(u"Caja")
        self.Caja.setAutoFillBackground(False)
        self.Caja.setStyleSheet(u"background-color:rgb(222, 221, 218)")
        self.tab_caja = QTabWidget(self.Caja)
        self.tab_caja.setObjectName(u"tab_caja")
        self.tab_caja.setGeometry(QRect(30, 120, 1161, 691))
        self.tab_caja.setStyleSheet(u"background-color:rgb(222, 221, 218);color:black")
        self.tab_venta = QWidget()
        self.tab_venta.setObjectName(u"tab_venta")
        self.contenedor_cuentas = QScrollArea(self.tab_venta)
        self.contenedor_cuentas.setObjectName(u"contenedor_cuentas")
        self.contenedor_cuentas.setGeometry(QRect(0, 70, 1161, 591))
        self.contenedor_cuentas.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1159, 589))
        self.horizontalLayoutWidget = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 1151, 581))
        self.HLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout.setObjectName(u"HLayout")
        self.HLayout.setContentsMargins(2, 1, 1, 1)
        self.contenedor_cuentas.setWidget(self.scrollAreaWidgetContents)
        self.label_search_2 = QLabel(self.tab_venta)
        self.label_search_2.setObjectName(u"label_search_2")
        self.label_search_2.setGeometry(QRect(10, 20, 70, 31))
        self.label_search_2.setFont(font2)
        self.inv_le_2 = QLineEdit(self.tab_venta)
        self.inv_le_2.setObjectName(u"inv_le_2")
        self.inv_le_2.setGeometry(QRect(200, 20, 491, 31))
        self.inv_le_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.inv_comboBox_2 = QComboBox(self.tab_venta)
        self.inv_comboBox_2.addItem("")
        self.inv_comboBox_2.addItem("")
        self.inv_comboBox_2.setObjectName(u"inv_comboBox_2")
        self.inv_comboBox_2.setGeometry(QRect(90, 20, 101, 31))
        self.venta_btn = QPushButton(self.tab_venta)
        self.venta_btn.setObjectName(u"venta_btn")
        self.venta_btn.setGeometry(QRect(1020, 20, 121, 31))
        self.venta_btn.setFont(font3)
        self.venta_btn.setAutoFillBackground(False)
        self.venta_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.venta_btn.setAutoRepeat(False)
        self.table_busq = QTableView(self.tab_venta)
        self.table_busq.setObjectName(u"table_busq")
        self.table_busq.setGeometry(QRect(200, 50, 491, 151))
        self.table_busq.setMinimumSize(QSize(491, 0))
        self.table_busq.setMaximumSize(QSize(491, 16777215))
        self.table_busq.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table_busq.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table_busq.setSortingEnabled(False)
        self.tab_caja.addTab(self.tab_venta, "")
        self.tab_inventario = QWidget()
        self.tab_inventario.setObjectName(u"tab_inventario")
        self.table_inv = QTableView(self.tab_inventario)
        self.table_inv.setObjectName(u"table_inv")
        self.table_inv.setGeometry(QRect(10, 60, 1141, 601))
        self.inv_le = QLineEdit(self.tab_inventario)
        self.inv_le.setObjectName(u"inv_le")
        self.inv_le.setGeometry(QRect(300, 10, 841, 31))
        self.inv_le.setContextMenuPolicy(Qt.NoContextMenu)
        self.inv_comboBox = QComboBox(self.tab_inventario)
        self.inv_comboBox.addItem("")
        self.inv_comboBox.addItem("")
        self.inv_comboBox.setObjectName(u"inv_comboBox")
        self.inv_comboBox.setGeometry(QRect(110, 10, 181, 31))
        self.label_search = QLabel(self.tab_inventario)
        self.label_search.setObjectName(u"label_search")
        self.label_search.setGeometry(QRect(30, 10, 71, 31))
        self.label_search.setFont(font2)
        self.tab_caja.addTab(self.tab_inventario, "")
        self.faltantes_tab = QWidget()
        self.faltantes_tab.setObjectName(u"faltantes_tab")
        self.table_falt = QTableView(self.faltantes_tab)
        self.table_falt.setObjectName(u"table_falt")
        self.table_falt.setGeometry(QRect(5, 1, 1151, 661))
        self.tab_caja.addTab(self.faltantes_tab, "")
        self.tab_estetica = QWidget()
        self.tab_estetica.setObjectName(u"tab_estetica")
        self.contenedor_esetetica = QScrollArea(self.tab_estetica)
        self.contenedor_esetetica.setObjectName(u"contenedor_esetetica")
        self.contenedor_esetetica.setGeometry(QRect(0, 70, 1161, 591))
        self.contenedor_esetetica.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 1159, 589))
        self.contenedor_esetetica.setWidget(self.scrollAreaWidgetContents_2)
        self.add_estetica_btn = QPushButton(self.tab_estetica)
        self.add_estetica_btn.setObjectName(u"add_estetica_btn")
        self.add_estetica_btn.setGeometry(QRect(20, 20, 131, 31))
        self.add_estetica_btn.setFont(font3)
        self.add_estetica_btn.setAutoFillBackground(False)
        self.add_estetica_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_estetica_btn.setAutoRepeat(False)
        self.tab_caja.addTab(self.tab_estetica, "")
        self.Logo_label_2 = QLabel(self.Caja)
        self.Logo_label_2.setObjectName(u"Logo_label_2")
        self.Logo_label_2.setGeometry(QRect(30, 20, 81, 81))
        self.Logo_label_2.setPixmap(QPixmap(u":/icon_small/CVIcaja.png"))
        self.stackedWidget.addWidget(self.Caja)
        self.Consul = QWidget()
        self.Consul.setObjectName(u"Consul")
        self.exit_btn_2 = QPushButton(self.Consul)
        self.exit_btn_2.setObjectName(u"exit_btn_2")
        self.exit_btn_2.setGeometry(QRect(10, 820, 171, 31))
        self.exit_btn_2.setFont(font3)
        self.exit_btn_2.setAutoFillBackground(False)
        self.exit_btn_2.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.exit_btn_2.setAutoRepeat(False)
        self.send_btn = QPushButton(self.Consul)
        self.send_btn.setObjectName(u"send_btn")
        self.send_btn.setGeometry(QRect(1030, 820, 171, 31))
        self.send_btn.setFont(font3)
        self.send_btn.setAutoFillBackground(False)
        self.send_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.send_btn.setAutoRepeat(False)
        self.Logo_label = QLabel(self.Consul)
        self.Logo_label.setObjectName(u"Logo_label")
        self.Logo_label.setGeometry(QRect(20, 10, 161, 161))
        self.Logo_label.setPixmap(QPixmap(u":/icon_mid/LogoMid.png"))
        self.mvz_lbl = QLabel(self.Consul)
        self.mvz_lbl.setObjectName(u"mvz_lbl")
        self.mvz_lbl.setGeometry(QRect(210, 100, 91, 31))
        self.mvz_lbl.setFont(font2)
        self.mvz_lbl.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.paciente_lbl = QLabel(self.Consul)
        self.paciente_lbl.setObjectName(u"paciente_lbl")
        self.paciente_lbl.setGeometry(QRect(210, 40, 91, 31))
        self.paciente_lbl.setFont(font2)
        self.paciente_lbl.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black")
        self.label = QLabel(self.Consul)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 190, 81, 31))
        self.label.setFont(font2)
        self.label.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.paciente_le = QLineEdit(self.Consul)
        self.paciente_le.setObjectName(u"paciente_le")
        self.paciente_le.setGeometry(QRect(330, 40, 701, 29))
        self.paciente_le.setFont(font2)
        self.paciente_le.setStyleSheet(u"color:black;")
        self.remove_btn = QPushButton(self.Consul)
        self.remove_btn.setObjectName(u"remove_btn")
        self.remove_btn.setGeometry(QRect(630, 820, 131, 31))
        self.remove_btn.setFont(font3)
        self.remove_btn.setAutoFillBackground(False)
        self.remove_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.remove_btn.setAutoRepeat(False)
        self.add_btn = QPushButton(self.Consul)
        self.add_btn.setObjectName(u"add_btn")
        self.add_btn.setGeometry(QRect(810, 820, 131, 31))
        self.add_btn.setFont(font3)
        self.add_btn.setAutoFillBackground(False)
        self.add_btn.setStyleSheet(u"background-color:rgb(53, 132, 228); color: rgb(246, 245, 244); border-radius:10px;")
        self.add_btn.setAutoRepeat(False)
        self.busq_consul_le = QLineEdit(self.Consul)
        self.busq_consul_le.setObjectName(u"busq_consul_le")
        self.busq_consul_le.setGeometry(QRect(280, 190, 491, 31))
        self.busq_consul_le.setStyleSheet(u"color:black;")
        self.mvz_comboBox = QComboBox(self.Consul)
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.addItem("")
        self.mvz_comboBox.setObjectName(u"mvz_comboBox")
        self.mvz_comboBox.setGeometry(QRect(330, 100, 271, 31))
        self.mvz_comboBox.setStyleSheet(u"color:black")
        self.busca_cuenta = QTableView(self.Consul)
        self.busca_cuenta.setObjectName(u"busca_cuenta")
        self.busca_cuenta.setGeometry(QRect(20, 240, 751, 521))
        self.busca_cuenta.setStyleSheet(u"color:black;")
        self.wrong_dr = QLabel(self.Consul)
        self.wrong_dr.setObjectName(u"wrong_dr")
        self.wrong_dr.setGeometry(QRect(330, 140, 171, 17))
        self.wrong_dr.setStyleSheet(u"color:red")
        self.label_cuenta = QLabel(self.Consul)
        self.label_cuenta.setObjectName(u"label_cuenta")
        self.label_cuenta.setGeometry(QRect(810, 190, 101, 31))
        self.label_cuenta.setFont(font2)
        self.label_cuenta.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.consul_comboBox = QComboBox(self.Consul)
        self.consul_comboBox.addItem("")
        self.consul_comboBox.addItem("")
        self.consul_comboBox.setObjectName(u"consul_comboBox")
        self.consul_comboBox.setGeometry(QRect(110, 190, 151, 31))
        self.consul_comboBox.setStyleSheet(u"color:black")
        self.wrong_pet = QLabel(self.Consul)
        self.wrong_pet.setObjectName(u"wrong_pet")
        self.wrong_pet.setGeometry(QRect(330, 70, 281, 17))
        self.wrong_pet.setStyleSheet(u"color:red")
        self.table_cuenta = QTableWidget(self.Consul)
        self.table_cuenta.setObjectName(u"table_cuenta")
        self.table_cuenta.setGeometry(QRect(800, 240, 401, 521))
        self.table_cuenta.setStyleSheet(u"color:black;")
        self.label_total = QLabel(self.Consul)
        self.label_total.setObjectName(u"label_total")
        self.label_total.setGeometry(QRect(800, 770, 231, 31))
        self.label_total.setFont(font2)
        self.label_total.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);color:black;")
        self.stackedWidget.addWidget(self.Consul)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.login_btn.setDefault(False)
        self.exit_btn.setDefault(False)
        self.tab_caja.setCurrentIndex(0)
        self.venta_btn.setDefault(False)
        self.add_estetica_btn.setDefault(False)
        self.exit_btn_2.setDefault(False)
        self.send_btn.setDefault(False)
        self.remove_btn.setDefault(False)
        self.add_btn.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.wrong_up_label.setText(QCoreApplication.translate("MainWindow", u"usuario \u00f3 contrase\u00f1a incorrectos", None))
        self.user_label.setText(QCoreApplication.translate("MainWindow", u"Usuario:", None))
        self.Pass_le.setText("")
        self.login_btn.setText(QCoreApplication.translate("MainWindow", u"Iniciar Sesi\u00f3n", None))
        self.exit_btn.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.pass_label.setText(QCoreApplication.translate("MainWindow", u"Contrase\u00f1a:", None))
        self.Login_combobox.setItemText(0, QCoreApplication.translate("MainWindow", u"Consultorio", None))
        self.Login_combobox.setItemText(1, QCoreApplication.translate("MainWindow", u"Caja", None))
        self.Login_combobox.setItemText(2, QCoreApplication.translate("MainWindow", u"Admin", None))

        self.label_search_2.setText(QCoreApplication.translate("MainWindow", u"Buscar:", None))
        self.inv_comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"productos", None))
        self.inv_comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"servicios", None))

        self.venta_btn.setText(QCoreApplication.translate("MainWindow", u"Nueva Venta", None))
#if QT_CONFIG(shortcut)
        self.venta_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_venta), QCoreApplication.translate("MainWindow", u"Venta", None))
        self.inv_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"productos", None))
        self.inv_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"servicios", None))

        self.label_search.setText(QCoreApplication.translate("MainWindow", u"Buscar:", None))
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_inventario), QCoreApplication.translate("MainWindow", u"Inventario", None))
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.faltantes_tab), QCoreApplication.translate("MainWindow", u"Faltantes", None))
        self.add_estetica_btn.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
#if QT_CONFIG(shortcut)
        self.add_estetica_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.tab_caja.setTabText(self.tab_caja.indexOf(self.tab_estetica), QCoreApplication.translate("MainWindow", u"Est\u00e9tica", None))
        self.Logo_label_2.setText("")
        self.exit_btn_2.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.exit_btn_2.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.send_btn.setText(QCoreApplication.translate("MainWindow", u"Enviar", None))
#if QT_CONFIG(shortcut)
        self.send_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.Logo_label.setText("")
        self.mvz_lbl.setText(QCoreApplication.translate("MainWindow", u"Doctor(a):", None))
        self.paciente_lbl.setText(QCoreApplication.translate("MainWindow", u"Paciente:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Servicio:", None))
        self.remove_btn.setText(QCoreApplication.translate("MainWindow", u"Quitar", None))
#if QT_CONFIG(shortcut)
        self.remove_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.add_btn.setText(QCoreApplication.translate("MainWindow", u"A\u00f1adir", None))
#if QT_CONFIG(shortcut)
        self.add_btn.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.mvz_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Seleccione", None))
        self.mvz_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"M.V.Z. Brenda", None))
        self.mvz_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"M.V.Z. Janeth", None))
        self.mvz_comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"M.V.Z. Juan", None))
        self.mvz_comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"M.V.Z. Luis", None))

        self.wrong_dr.setText(QCoreApplication.translate("MainWindow", u"Seleccione quien atendi\u00f3", None))
        self.label_cuenta.setText(QCoreApplication.translate("MainWindow", u"Cuenta:", None))
        self.consul_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"servicios", None))
        self.consul_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"productos", None))

        self.wrong_pet.setText(QCoreApplication.translate("MainWindow", u"Ingrese nombre de mascota o propietario", None))
        self.label_total.setText(QCoreApplication.translate("MainWindow", u"Total: $", None))
    # retranslateUi

